### ISSUE TITLE
Script on platforms

### ISSUE THREAD

**Issue by Fehertukor** [OctoNezd/oldlander#10]
Hello!

Thank you for your work!
I followed your instructions but I can't install the script with violenmonkey() from local file.

Would it be possible to out put your script on
https://greasyfork.org/
?
That would help a lot!

Thank you!

**Comment by OctoNezd** [comment]
That's weird - TamperMonkey on last Firefox mobile detects user.js just
fine when I click on user.js release. I will check ViolentMonkey later
today. Meanwhile check if you try to install latest release - some older
ones had glitchy header that bugged iOS userscripts app out.

I plan to release it on GreasyFork once I figure out if they have API - all
public builds of OldLander are done via CI and I would prefer keeping
manual intervention to a minimum.

**Comment by OctoNezd** [comment]
Just checked ViolentMonkey on Kiwi - all detects and installs fine there

**Comment by Fehertukor** [comment]
Thank you for your answer!
I checked without tampermonkey and that works in firefox Android flawlessly. But in violentmonkey it is still impossible(there is no option) to import the scrip locally,  sadly.

**Comment by OctoNezd** [comment]
When you click on user.js does it just open script file or attempt to download it?

**Comment by Fehertukor** [comment]
First I fixed my previous comment.

It is a mystery, cleared browser data and tried again to click it and now it works!...

Thank you for your time!

Solved.
