### ISSUE TITLE
Increase size of comment collapse button 

### ISSUE THREAD

**Issue by Milligray** [OctoNezd/oldlander#110]
The comment collapse button (-) is too small. This results in miss-taps on the comment user name. I'm suggesting two options:

A.) Larger comment collapse button.
B.) Tapping a portion of the comment to collapse entire comment.

![Screenshot_20240121-142250](https://github.com/OctoNezd/oldlander/assets/139649568/8047175a-82dd-4a25-bd22-e2b6e975ce79)
.

**Comment by OctoNezd** [comment]
Hi. Tapping the sideline of comments automatically hides them. I might try increasing the font size and weight of button later on, see how it would turn out

**Comment by Milligray** [comment]
Any updates on this? 

The collapse button is too small so I am constantly tapping on the username or the reply button. I never login to reddit, so I always get a pop-up to sign up for an account. 

> Hi. Tapping the sideline of comments automatically hides them. I might try increasing the font size and weight of button later on, see how it would turn out

**Comment by sudoshindo** [comment]
Potential solution:

- increase padding left and right to make it easier to hit
- also increase margin right to push the username away and make it harder to accidentally hit

**Comment by OctoNezd** [comment]
All android clients i know of just require holding onto comment and dont even have the button to do that in first place. I think I will copy that behavior

**Comment by zwazi** [comment]
There is a setting in RES that works pretty well for this. It's `Toggle Commends On Click Left Edge`, it replaces the collapse button with a bar on the left edge of the comment. You also need to disable the `Comment Style` category in RES, or it will block the first half column of text in each comment. 

Ideally, I'd like to keep the comment style enabled cause it looks better, but it's better than nothing, I suppose.

![Screenshot_20240530-141434](https://github.com/OctoNezd/oldlander/assets/5894449/6f2f32fd-758d-458b-962c-ffcf838f46d0)

⬆️ With Comment Style Disabled
⬇️ With Comment Style Enabled

![Screenshot_20240530-140811](https://github.com/OctoNezd/oldlander/assets/5894449/77b111af-541a-41e9-8d7a-416cef462a88)

**Comment by sudoshindo** [comment]
> Potential solution:
> 
> * increase padding left and right to make it easier to hit
> * also increase margin right to push the username away and make it harder to hit the wrong thing

https://codeberg.org/ransan/ransan-userscripts/src/branch/master/oldlander-style-tweak.user.js

Temporary solution for anyone that wants it.

**Comment by sudoshindo** [comment]
![Screenshot_20240630-204600](https://github.com/OctoNezd/oldlander/assets/97193233/cbfe4129-b012-4ebd-a794-48da8b760d8c)

So how exactly do I get this update ASAP?

I don't know where they put the extension update button on mobile.

**Comment by OctoNezd** [comment]
Try re-installing extension, perhaps?

**Comment by sudoshindo** [comment]
![Screenshot_2024 07 01_054848](https://github.com/OctoNezd/oldlander/assets/97193233/9e07d631-73b3-4541-9b6d-418df9521852)

@OctoNezd my dude, you used the wrong selectors, the default padding has higher specificity.

I'd also like to suggest adding `margin-right: 6px;` to further lower the chances of tapping the username on accident.

Reference: [my userscript](https://codeberg.org/ransan/ransan-userscripts/src/branch/master/oldlander-style-tweak.user.js)
