### ISSUE TITLE
Caption does not show up on image posts with caption

### ISSUE THREAD

**Issue by KompaktiLevy** [OctoNezd/oldlander#114]
**Describe the bug**
Posts that have an image and a caption should show the caption when clicked on, but it is not shown on oldlander. There seemingly is no way to tell if an image post has a caption or not.

**To Reproduce**
1. Go to any image post with a caption with oldlander **disabled**. [Example post](https://old.reddit.com/r/headphones/comments/18vgt5g/got_this_for_christmas_do_they_even_make_music/)
2. Observe caption - the example post should have a caption at the bottom which reads the following:

> If my music is 24 bit 192 khz , what would this do to the music then? Would it just play at 24 bit 192 or would it upscale to 32 bit 384 khz? Im confused at what it does. Just confused on how it encodes the music if we dont even have that on a consumer level.  

(Screenshot below)

3. **Enable** oldlander and **refresh the page**
4. The caption is gone

(Screenshot below)

**Expected behavior**
The caption should not be gone

**Screenshots**
![Observe the caption](https://github.com/OctoNezd/oldlander/assets/150954777/28b59639-1af0-4404-8a61-6a5a48b72326)
_Notice the caption at the bottom_

![Where is it?](https://github.com/OctoNezd/oldlander/assets/150954777/f9db32d3-64fa-4d71-a845-04d77fd53afa)
_The caption is gone. (Screenshot taken on desktop, but it's the same on mobile. I don't use this on desktop.)_

**Desktop:**
 - OS: Linux Mint 21.3 Cinnamon
 - Browser: LibreWolf
 - LibreWolf version: 121.0-1
 - Oldlander version: 1.1.0.480

**Smartphone:**
 - Device: Samsung Galaxy A71 5G, OnePlus 5T
 - OS: Android 12 (One UI 5.1), DivestOS 20 (Android 13)
 - Browser: Firefox, Mull
 - Browser version: 121.1.0
 - Oldlander version: 1.1.0.480

**Reddit page where bug can be easily reproduced**

[Same as example post linked before](https://old.reddit.com/r/headphones/comments/18vgt5g/got_this_for_christmas_do_they_even_make_music/)
[Another one](https://old.reddit.com/r/headphones/comments/191tn41/why_is_andrew_testing_the_he1_with_spotify_is_he/)
[Another one](https://old.reddit.com/r/headphones/comments/18y487v/the_beats_fit_pro_suck_actual_ass/)

**Additional context**
This is a very major problem on some subreddits. Perhaps I'm just missing where to find the caption, but I have yet to find it on any post.

**Comment by OctoNezd** [comment]
IIRC the caption is displayed as part of expando, and oldlander removes expandos. I will try to make it keep the caption.
