### ISSUE TITLE
Up/down vote buttons for post intermittently do not register

### ISSUE THREAD

**Issue by amicitas** [OctoNezd/oldlander#119]
**Describe the bug**
When I press the up/down vote button for a post my vote usually does not register. When I press the button it highlights as expected but when I refresh the page, the vote dissappears. After a few attempts at voting and refreshing eventually the vote will register. 

**To Reproduce**
1. Vote for a post in the subreddit page or comments page. 
2. Refresh page. 

**Expected behavior**
Vote registered and is displayed after page refresh or moving between pages. 

**Smartphone (please complete the following information):**
 - Device: Pixel 7 Pro
 - OS: Android 14
 - Firefox
 - 122.0.1 (Build #2016000543), c67c9e840c+
 - Firefox Nightly
 - 124.0a1 (Build #2016001031), 8d23695305+
 

If applicable, add reddit link here where you can easily reproduce bug.

**Additional context**
Same problem on both Firefox and Firefox Nightly. This issue only exists when Oldlander extention is enabled.

**Comment by OctoNezd** [comment]
Merged into #165
