### ISSUE TITLE
Request for feature: icon to open multireddit navbar

### ISSUE THREAD

**Issue by ckl33** [OctoNezd/oldlander#12]
I'm not sure to what extent you are able to edit the old reddit layout, but:

I'm trying to recreate the RIF experience as best as I can in Firefox Nightly using your extension + uBlock Origin + RES. I was wondering if you would be able to add a hamburger menu icon for opening the multireddits navbar to replace the existing 'tap left edge of screen to open' implementation that reddit has by default. Their default implementation is usable, but its kind of a nightmare with Android gesture control with accidentally going back when trying to open the navbar or vice versa.

Just to show what I am trying to recreate, please see these images:

Subreddit manager shortcut hamburger menu icon (circled in red) in RIF: 
![rif1](https://github.com/OctoNezd/oldlander/assets/33946955/08f3bf8a-7f3c-4015-a144-4e088e7ca57b)
Subreddit manager opens when tapped in RIF, shows favourited (starred) subreddits on top:
![rif2](https://github.com/OctoNezd/oldlander/assets/33946955/be2c9f6a-0a69-4f7a-a661-1b1ff9f57f59)

Currently what appears in old.reddit with oldlander (multireddit navbar shortcut circled in red):
![old1](https://github.com/OctoNezd/oldlander/assets/33946955/25a38891-02e8-4668-a2a0-93db991c4184)
Multireddit navbar that opens when that left edge button is tapped in old.reddit:
![image](https://github.com/OctoNezd/oldlander/assets/33946955/4f589118-508a-4226-8070-7a451bf00630)
What I'm hoping you could implement:
![change1](https://github.com/OctoNezd/oldlander/assets/33946955/5250d401-ad18-44f2-a059-f320f5de0220)

Thank you for reading my request.

For anyone interested in trying to recreate the RIF layout on mobile old.reddit like I am, I've done the below so far:

1. Since on mobile, the top subreddit shortcut bar is near unusable since it's so tiny if you have more than a few shortcutted subreddits, I decided to get rid of it completely. I was able to hide the top subreddit shortcut bar by using uBlock Origin element picker + filtering out elements until it was gone entirely.
2. To emulate "favourited" subreddits, i created multireddits with the same name of each of my favourite subreddits and just added the lone subreddit to each multireddit, so that the left side pullout multireddit bar is actually useful since the icons are a good size for mobile browsing compared to that top subreddit bar.
3. Haven't found a way yet to easily add other non-favourited, but subbed subreddits below the multireddits or a way to easily make the 'My Subreddits' shortcut mobile-friendly
4. When opening videos using that RES shortcut, if its a v.redd.it video, you can click 'Disable Host' on the popup and then v.redd.it videos will work

**Comment by OctoNezd** [comment]
![image](https://github.com/OctoNezd/oldlander/assets/15308404/8c42d1ec-c357-49e0-a9aa-8386bfb81d55)

👀

**Comment by OctoNezd** [comment]
![image](https://github.com/OctoNezd/oldlander/assets/15308404/35dd8681-aa03-4563-8e54-f2e649929666)
a more refined version

**Comment by OctoNezd** [comment]
Done in latest version

**Comment by faraplay** [comment]
Would it be possible to make it so that this navbar can be opened with a left swipe action, similar to the right sidebar?

**Comment by OctoNezd** [comment]
I will most likely remove the right sidebar and turn it into a button, so
swipes will be free to use for a proper sidebar

**Comment by OctoNezd** [comment]
Implemented in a82a0a1
