### ISSUE TITLE
Enter/newline key does not register a newline in comments

### ISSUE THREAD

**Issue by ketura** [OctoNezd/oldlander#127]
In Firefox beta on android, attempting to press the enter/newline key results in a space upon first press and no whitespace at all on subsequent presses. This makes writing comments a drag, as you are limited to a single paragraph. Even copy-pasting text with newlines appears to have them removed. 

Each newline press does result in a character being added (which you can tell by pressing backspace). Suspect perhaps a CSS thing. 

**To Reproduce**
1- open any thread
2- attempt to leave a comment. Use the enter key or paste in material with multiple newlines
3- observe that the text box has ignored all newline input 

**Expected behavior**
Newlines should behave as they do in every text app ever. 

**Screenshots**
![Screenshot_2024-03-22-13-25-38-66_ffb2f5e1b976ff98cfc94f359fbce8de](https://github.com/OctoNezd/oldlander/assets/1814132/3935dfd9-507c-4bed-bd06-d28cc115b617)

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord N30 5G
 - OS: Android 14
 - Browser: Firefox Beta
 - Version: 124.0b9 (Build #2016007959), b1c5673fd5+

**Comment by OctoNezd** [comment]
Can confirm on latest, not present in normal reddit. Weird - I dont remember ever modifying input box behavior on reddit.

**Comment by ketura** [comment]
I just confirmed that the newlines are in fact preserved in the submitted message, they just don't look any different from spaces in the text box:

![Screenshot_2024-03-22-14-00-55-81_ffb2f5e1b976ff98cfc94f359fbce8de](https://github.com/OctoNezd/oldlander/assets/1814132/9e675da4-17b8-4c85-bcc0-28c581030eaa)

![Screenshot_2024-03-22-14-01-14-90_ffb2f5e1b976ff98cfc94f359fbce8de](https://github.com/OctoNezd/oldlander/assets/1814132/cc9839f3-53b4-4696-be4e-c5c48a91c892)

I am now more suspicious of it being a CSS thing that is perhaps crushing the vertical padding of <p> or <div> tags to 0, or something. Some selector meant for one of the menu bars incorrectly matching something about the text box, or something.

**Comment by OctoNezd** [comment]
It's caused by `white-space: unset` on `textarea`. I dont remember why I put it there, gonna remove that.
