### ISSUE TITLE
Option to switch to old UI

### ISSUE THREAD

**Issue by jaeyoung-j** [OctoNezd/oldlander#133]
I preferred the UI before the update on 2024-03-24, where the vote count and comment count would be shown with the vote and comment buttons instead part of the small text. I know that the comment count can be shown with the comment button with the new "Display comment count on comment icon" setting, but I have not found an equivalent for the vote count.

I would like if an equivalent setting could be added for the vote count.

I have considered downgrading the addon in Firefox, but I have not found a way to downgrade addons or sideload .xpi files in mobile Firefox.

**Comment by OctoNezd** [comment]
Implemented.
