### ISSUE TITLE
Point totals are incorrect

### ISSUE THREAD

**Issue by Cobra800089** [OctoNezd/oldlander#144]
**Describe the bug**
Since I updated to 1.1.0.500 point totals for my user seem to be showing 1 less than what they actually are. For example when I post a new comment it immediately shows it at 0 points even though the upvote button is highlighted. When I check the comment in a different browser without OldLander it correctly displays 1 point.

If I view my user's profile with OldLander every comment shows 1 point less than with a different browser without OldLander.

**To Reproduce**
1. Post a comment 
2. See that it immediately shows 0 points.

**Expected behavior**
Point totals to be correct, comments showing as 1 point immediately after posting.

**Smartphone (please complete the following information):**
 - Pixel 6 Pro
 - Android 14 - Build: AP1A.240405.002
 - Browser: Fennec
 - Version 124.2.0

**Comment by OctoNezd** [comment]
Merged into #165
