### ISSUE TITLE
Dyslexia add-on interfering with Oldlander's icons

### ISSUE THREAD

**Issue by Dolinmyster** [OctoNezd/oldlander#145]
**Describe the bug**
I have mild Dyslexia, and although I don't require the use of a Dyslexia font to fully function, it does help me in my day to day life. If I have the Dyslexia add-on active for some reason all the buttons turn into words and the icons are replaced. This is clearly caused by a different add-on as disabling it fixes this, but I still wanted to report it here. I plan to make a report of it over there as well so hopefully one of you can discover what is causing it. 

This is the add-on in question
https://addons.mozilla.org/en-US/firefox/addon/mobile-dyslexic/

Edit Note: So I just checked the plug in and it hasn't been updated for five years. So it's unlikely to get any traction from that dev. If it's not something that can be realistically resolved, could an enhancement be created to possibly give oldlander a dyslexia option?

**To Reproduce**
1. Enable Oldlander and Dyslexia Mobile
2. Open Reddit
3. View words in place of icons

**Expected behavior**
Expected that the words on the screen are enhanced with a Dyslexia font for easier reading

**Screenshots**
add-on enabled
![image](https://github.com/OctoNezd/oldlander/assets/8488882/d83c5a31-45d3-436b-ae6b-7411a422a6a4)
add-on disabled
![image](https://github.com/OctoNezd/oldlander/assets/8488882/00071d2f-66ea-458a-b5ed-08f88ef5267d)

**Smartphone (please complete the following information):**
 - Pixel 8 Pro
 - OS: GrapheneOS [2024042200](https://grapheneos.org/releases#2024042200)
 - Browser: Firefox
 - Version 125.3.0

**Additional context**

**Comment by OctoNezd** [comment]
Looking at Mobile Dyslexic addon source code one of fixes might be to apply OWA class to icons and shrug it off:

![image](https://github.com/OctoNezd/oldlander/assets/15308404/5a03e8dd-0e44-4866-ba78-600bf0b33c49)

But I will also implement font picker inside the addon, with opendyslexic as option.

**Comment by OctoNezd** [comment]
Wait no owa class seems to be needed, just as long as class has `icon` in its name can help with that compatibility.
