### ISSUE TITLE
Wiki pages and user page comment threads are unreadable

### ISSUE THREAD

**Issue by carlos-h-h** [OctoNezd/oldlander#149]
**Describe the bug**
When viewing wiki pages or user page comment threads, the same problem happens: the content is squeezed to the leftmost 10% of the screen, making it unreadable.

**To Reproduce**
1. Go to https://old.reddit.com/r/reddit/wiki/index
2. See the bug happening on a wiki page.
3. Go to https://old.reddit.com/user/Chtorrr/comments/u2zguk/flowers/
4. See the bug happening on a user page comment thread.

**Expected behavior**
The content should be displayed using the full screen width, as in normal comment threads.

**Smartphone (please complete the following information):**
 - Device: Samsung S20
 - OS: Android 12
 - Browser: Firefox
 - Version: 125.2.0

**Reddit page where bug can be easily reproduced**

https://old.reddit.com/r/reddit/wiki/index (wiki)

https://old.reddit.com/user/Chtorrr/comments/u2zguk/flowers/ (user page comment thread)

**Comment by OctoNezd** [comment]
Fixed.
