### ISSUE TITLE
Userscript not not working in Adguard

### ISSUE THREAD

**Issue by blogmangit** [OctoNezd/oldlander#162]
**Describe the bug**
Oldlander userscript not working with Adguard android which has userscript support.

**To Reproduce**
1. install Oldlander on adguard
2. install old reddit redirect
3. Oldlander not activated

**Expected behavior**
Oldlander should activate

**Screenshots**
![29_06_2024_15_11_38](https://github.com/OctoNezd/oldlander/assets/92579403/d170d1ff-12f1-4279-b8de-f3c43e38748b)

**Desktop (please complete the following information):**
Not Applicable 

**Smartphone (please complete the following information):**
 - Device: [Samsung M12]
 - OS: [Android 13.1]
 - Browser:  [Google Chrome] 
 - Version [127]

**Reddit page where bug can be easily reproduced**
https://old.reddit.com/r/Android/comments/18wm7tp/octonezdoldlander_firefox_addon_to_make_old/

If applicable, add reddit link here where you can easily reproduce bug.
https://old.reddit.com/r/Android/comments/18wm7tp/octonezdoldlander_firefox_addon_to_make_old/

**Additional context**
Not Applicable

**Comment by OctoNezd** [comment]
Check latest version - should work correctly.

**Comment by blogmangit** [comment]
> Check latest version - should work correctly.

Tried the latest version it's working but the preferences are not getting saved.

**Comment by OctoNezd** [comment]
Preference arent getting saved probably cause AdGuard userscript engine doesn't provide engine. I will try to add fallback for that later on.
