### ISSUE TITLE
Parent comment button

### ISSUE THREAD

**Issue by edggoncalves** [OctoNezd/oldlander#163]
**Is your feature request related to a problem? Please describe.**
When you find a user's comment you want to know the context of, you have a button that takes you to the comment in the thread. Unfortunately this doesn't show the parent comment, when there is one. 

**Describe the solution you'd like**
I've seen in other interfaces, when you follow the link of the comment to the thread, a button which expands either the parent comment, or the whole tree the comment is a part of. Either or both buttons would be a very nifty feature!

**Comment by carlos-h-h** [comment]
If you mean going from an user's comments page to the original thread, there's actually an invisible "context" button between the "save" (floppy disk) and "go to post" (fenced square) buttons. Just tap between those and it'll send you to the comment inside the thread with a context of 3 parent comments.

**Comment by edggoncalves** [comment]
I didn't know about this hidden button, but even then, when I tap that, it shows that comment as the parent of the displayed thread, and never the previous comments, unless you tap "view the rest of the comments" which just shows the whole comments section of the post.

I do see a new (recent?) button which seems to do exactly what I was looking for, to the right of the floppy disk :)
