### ISSUE TITLE
Context button lacks icon

### ISSUE THREAD

**Issue by carlos-h-h** [OctoNezd/oldlander#164]
**Describe the bug**
On a user's comment page, comments have two buttons to go to the original thread: "context" and "full comments". The former doesn't have an icon and is rendered invisible.

I think it's here:

https://github.com/OctoNezd/oldlander/blob/d51a2857a7db7f24be89b43c1da2729d9ea47192/src/features/posts/css/postIcons.css#L137-L139

If you aren't sure what icon to choose, I suggest "Menu Open".

Thanks.

**Comment by OctoNezd** [comment]
Thanks! I probably copy pasted code and didnt notice the button going missing.
