### ISSUE TITLE
Oldlander .js file install issue.

### ISSUE THREAD

**Issue by SpazMahTazz** [OctoNezd/oldlander#22]
**Describe the bug**
I've tried the Tampermonkey version on normal Firefox but it doesn't really work. [It ends up looking like this](https://i.postimg.cc/1R58D8rT/2023-7-2-17-33-38.png). All I did was click the .js in the Github releases page though, did I miss a step?   
Ps, it looks great on Firefox Nightly though!

**To Reproduce**
1. Click on the .js file in normal Firefox for Android
2. Let Tampermonkey install it
3. Go to Reddit

**Expected behavior**
Should look like the screenshots posted in the readme but it doesn't

**Screenshots**
https://i.postimg.cc/1R58D8rT/2023-7-2-17-33-38.png

**Smartphone (please complete the following information):**
 - Device: BlackBerry Key2
 - OS: Android 8.1
 - Browser: Normal Firefox
 - Version: 114.2.0

**Additional context**
It works and looks great on Firefox Nightly though!

**Comment by OctoNezd** [comment]
Are you using old.reddit.com? Just checked addon on firefox desktop - all looks fine.

**Comment by SpazMahTazz** [comment]
I was using [this](https://greasyfork.org/en/scripts/40897-old-reddit-please) to get old reddit working because there's no add-on for normal Firefox to make it work. But even turning it off and doing it manually is still not working.

It seems like it's not adjusting for the screen size properly or something like that.
https://i.postimg.cc/FFDf1xXq/Screenshot-20230704-075152.png

**Comment by faraplay** [comment]
The code to change the viewport wettings was changed in pull request #24, are you still encountering this problem?

**Comment by SpazMahTazz** [comment]
> The code to change the viewport settings has been changed in pull request #24, are you still encountering this problem?

No the issue is fixed now, thanks for letting me know!
