### ISSUE TITLE
Apply styles etc. on document_start

### ISSUE THREAD

**Issue by faraplay** [OctoNezd/oldlander#23]
**Is your feature request related to a problem? Please describe.**
When the page is loading on a phone, it takes a few seconds for the styles, sidebars etc to load in. This means that every time I click on a post, a bright screen with the original sidebar taking up almost all of the screen is the first thing I see.

**Describe the solution you'd like**
Ideally, the page would appear mobile-friendly from the start.

**Describe alternatives you've considered**
Making the extension run at `document_start`, and adding CSS through the `manifest.json` rather than via `style-loader` might fix this.
Existing code may need to be rewritten since many elements (e.g. `head`, `body`) are not yet present at `document_start`.

**Additional context**
I've been trying to work on a fix for this myself, so I may create a pull request for this issue at some point.

**Comment by OctoNezd** [comment]
I experimented with that before, and biggest problem is viewport. Also it would be nice to intercept subreddit CSS network request, but compatibility with user.js might degrade.
