### ISSUE TITLE
Flairs are hard to read

### ISSUE THREAD

**Issue by faraplay** [OctoNezd/oldlander#26]
**Describe the bug**
Some flairs are hard to read due to the text in them having colour depending on light/dark theme rather than flair colour.

**To Reproduce**
1. Go to a subreddit with different colour flairs
2. Set light/dark mode
3. Struggle to read flairs

**Screenshots**
See example of the same post in light & dark mode below. The flair text is easy to read in dark mode but very hard to read in light mode.
![grond-dark](https://github.com/OctoNezd/oldlander/assets/65869253/27ff618b-63cd-4edc-b8fa-5f27eba470a6)
![grond-light](https://github.com/OctoNezd/oldlander/assets/65869253/85a6a88f-5ed5-469c-bc0c-74e0d5f65fa7)

**Comment by faraplay** [comment]
Issue seems to be resolved as of version 1.1.0.130

**Comment by OctoNezd** [comment]
Weird, 1.1.0.130 just merged the user.js document-start though?

**Comment by OctoNezd** [comment]
Perhaps subreddit changed flair configuration?

**Comment by faraplay** [comment]
It seems that the custom style loader is loading the application's CSS before Reddit's, meaning that Reddit's stylings now take priority.
This also means that the nested comment indent is now what it was before (see pull request #18)

**Comment by OctoNezd** [comment]
As a possibility we can include css twice, once before DOMContentLoaded, and once after. I will try that this weekend

**Comment by faraplay** [comment]
Yeah, that sounds better than what I had in mind, which was adding a lot of `!important` in the CSS everywhere.

The DOMContentLoaded event might be too late for the second CSS addition, since it only fires after all posts are loaded in.
It might be better to re-add the CSS as soon as the last child of the header is loaded, which is a `<style>` tag:
![image](https://github.com/OctoNezd/oldlander/assets/65869253/f0cb9129-70db-4ecd-850d-c7b886212400)
This should be possible by awaiting the `querySelectorAsync` utility function.
