### ISSUE TITLE
Preferences page is broken

### ISSUE THREAD

**Issue by faraplay** [OctoNezd/oldlander#29]
**Describe the bug**
The preferences page is missing some options. It is also missing the "save options" button, meaning that preferences can't be changed.

**To Reproduce**
1. Go to preferences page

**Expected behavior**
See options, sorted by sections: 
- interface language
- clicking options
- media
- link options
- comment options
- messaging options
- email options
- display options
- content options
- privacy options
- personalisation options
- beta options
- "save options" button

**Actual behaviour**
Only the sections up to messaging options are seen. Notably, the "save options" button is missing.

**Browser details**
Version of oldlander used was 1.1.0.130

**Comment by OctoNezd** [comment]
Options sorted by sections are probably under sort button? Probably need to change that icon on preferences page to something else

**Comment by faraplay** [comment]
Oh, I meant the options tab specifically, I hadn't actually noticed the other tabs. But other tabs on the preferences page do need styling too.

Here are some screenshots of what I'm talking about, notice how the later options are missing from the page.

Expected | Actual
--------|-----------
![options_fixed](https://github.com/OctoNezd/oldlander/assets/65869253/030dd87e-c6e8-4bdc-b12c-b0ac141c06f8) | ![options_oldlander](https://github.com/OctoNezd/oldlander/assets/65869253/af4230a1-7c34-4588-a346-e67715a277d8)
