### ISSUE TITLE
no list of subreddits

### ISSUE THREAD

**Issue by wogglenet** [OctoNezd/oldlander#34]
On the fly out menu on the left, there's a header for subreddits, but under it I only have the option for random and randomnsfw. I am logged in. None of my subscribed subreddits are listed.

Additionally, consider adding an input box for going to a new subreddit via entering the name.

**Expected behavior**
List of subscribed subreddits

**Os
Android Firefox nightly

**Comment by OctoNezd** [comment]
Can you connect your phone to desktop Firefox, enable USB debug in both Firefox and Android, go to about:debugging on PC, select phone, open reddit and show me Storage - Local Storage tab?

**Comment by wogglenet** [comment]
I haven't had a chance to do that yet, but I can report that this works now, oddly enough. It wasn't working for hours, but I went back to it now and pulled to refresh and they all showed up. They are not alphabetically ordered though. Would this be possible to add?

**Comment by OctoNezd** [comment]
Most likely the subreddit cache got corrupted. 

Yes, sorting would be possible. 

I plan on adding settings UI this week that will also have option to manually flush cache and toggle sorting.

**Comment by OctoNezd** [comment]
Split into #35 and #36
