### ISSUE TITLE
Jitter on header bar

### ISSUE THREAD

**Issue by wogglenet** [OctoNezd/oldlander#41]
**Describe the bug**
Touch inputs on some phones jitter a bit with slow scrolling. For this reason, having a header bar that auto hides also needs some degree of slop detection, basically requiring a change in direction of scrolling and a set number of pixels, say 10 or something, before changing the state of the auto hide.

**To Reproduce**
Scroll slowly. Auto hide freaks out

**Expected behavior**
Doesn't freak out

**Screenshots**
Will try to attach video https://streamable.com/twkms4

**Smartphone (please complete the following information):**
 - Device: note20ultra
 - Browser ff nightly

**Additional context**

**Comment by OctoNezd** [comment]
Should be fixed in last version - please check.

**Comment by wogglenet** [comment]
Nope, it still constantly goes up and down, although it no longer "freaks out" (it doesn't skip the animation anymore). What I would do to solve it, and if you look carefully at the firefox URL bar in android, this is how it works as well, is actually to translate by the amount scrolled up to a max. So like instead of using

.animate([{ top: "-48px" }, { top: 0 }], {

just keep a variable or obtain the current state of top, and then add prevscrollpos-curscrollpos to the top attribute until it reaches a maximum or minimum of 0 or -48. This will make it seem like it "sticks" to the page, and this is how native android auto hiding toolbars work and behave (like the firefox url bar, except that one is in reverse since it is a bottom toolbar).

So just get rid of animate entirely and translate it pixel by pixel according to the amount scrolled. 

I think that will get the desired effect

**Comment by OctoNezd** [comment]
The most ideal solution would be [scroll-based animation](https://caniuse.com/?search=scroll-driven), but FF or Safari doesn't support it yet

**Comment by OctoNezd** [comment]
Implemented scroll behavior as you suggested - please check it.

**Comment by wogglenet** [comment]
This fixes the issue further down the page but now exhibits an odd jumping near the top of the page on v144.

I am not a CSS or JS expert. But, I am guessing that you are switching between the div between being fixed and sticky, and this is causing a recalculation of the content of the page and therefore the scroll location when this change occurs. This results in a sudden shift of the content when this change occurs. It may work to leave an empty "block" of some kind with a fixed height of 48 that "keeps" a space open for the header, and then leave the header itself as fixed at all times with only adjustments to top. Again, not an expert.

**Comment by faraplay** [comment]
Another thing: as it is now (1.1.0.152), if you scroll a little bit you can leave the header half-visible, which isn't ideal. Maybe you could animate the header to move to 0 or 48px (whichever is closer) on a touchend event or something?

**Comment by wogglenet** [comment]
I would recommend replicating the behavior of the Firefox nightly URL toolbar, which is to snap up or down when the finger is released from the screen, depending on which state is closer
