### ISSUE TITLE
Collapse-preview button moves to corner of screen for some non-fullscreen previews

### ISSUE THREAD

**Issue by faraplay** [OctoNezd/oldlander#45]
**Describe the bug**
When some things are previewed (e.g. youtube videos when RES is disabled, image galleries when RES is enabled), the expando button moves to the top right corner of the screen despite the preview not being full-screen.

**Expected behavior**
The expando button should be in the top right corner if and only if the preview is full-screen.

**Screenshots**
Note the X button in the top right corner in both screenshots.
Youtube video, RES disabled | Image gallery, RES enabled
-----------------------------|----------------------------
![youtube-preview](https://github.com/OctoNezd/oldlander/assets/65869253/148eddfd-63d5-4b23-84da-37b55869476d) | ![gallery-preview](https://github.com/OctoNezd/oldlander/assets/65869253/0b0ea66b-0e94-4e4b-afda-e60f59030f33)

**Comment by OctoNezd** [comment]
It seems that all 3rd-party expandos are broken now. Uh oh.
