### ISSUE TITLE
Page scrolls when fullscreen preview is open

### ISSUE THREAD

**Issue by faraplay** [OctoNezd/oldlander#46]
**Describe the bug**
When a fullscreen preview is open, trying to scroll up or down will result in the page behind scrolling. This is not expected behaviour of a fullscreen preview, and it can be annoying when you lose track of where the post you were looking at went.

**Expected behavior**
The page should not scroll if a fullscreen preview is open.

**Version**
Version used was 1.1.0.152

**Comment by wogglenet** [comment]
This also happens for modals
