### ISSUE TITLE
Back button could be consumed by image preview?

### ISSUE THREAD

**Issue by wogglenet** [OctoNezd/oldlander#51]
This would be pretty low priority

**Is your feature request related to a problem? Please describe.**
Often my brain tells me to hit the back button when in a full screen preview

**Describe the solution you'd like**
The back button causes the image preview to close rather than the browser actually going back

**Comment by ketura** [comment]
Seconding this. Muscle memory from every other app in existence is a hassle on thus extension, since it always navigates back instead of dismissing image.

**Comment by OctoNezd** [comment]
Implemented in latest version
