### ISSUE TITLE
Overlapping context menus on top right side with res installed. 

### ISSUE THREAD

**Issue by polo2005x** [OctoNezd/oldlander#65]
**Describe the bug**
![Screenshot_20230808_003231_Firefox Nightly](https://github.com/OctoNezd/oldlander/assets/72583826/8506b95c-b9e5-41c1-9c7d-25a4b806311a)

Res mail menu is overlapping the native menu for sorting on the top right side.

**To Reproduce**
1. Download tampermoneky on ff nightly android. 
2. Install script from release 
3. Install res

**Smartphone (please complete the following information):**
 - Device: samsung s23
 - OS: stock
 - Browser ff nighty 118.0a1 Build #2015966659

**Additional context**
 I used to have the rest top bar, did you decide to remove it? Was very useful for quick navigation.

Is it possible to re-enable the res subreddit manager as it's superior to the left swipe menu and scroll to the bottom to access your sub reddit.

**Comment by MHzBurglar** [comment]
I also have this issue, and it makes using both Old Lander and RES features difficult.  A potential workaround for now, if you don't mind losing the RES 'widgets' at the top of the page, is to disable the following in RES:

- Browse by Wheel feature
- Unread Messages feature
- Page Navigator: disable the "To Top" and "To New Comment Area" buttons
- Never-Ending Reddit: disable the "Pause" button

Though it limits some RES functionality, it does get rid of all the RES elements which conflict with Old Lander's buttons

**Comment by OctoNezd** [comment]
I think the good solution for RES would be to move its buttons into floating action buttons. Hide the browse by wheel, obviously, cause addon is mobile-first.

**Comment by OctoNezd** [comment]
Fixed in 55039d2 and 6dffac6
The up button is moved into titlebar text, like in other apps. Mail button doesn't work on touchscreens (seems to use hover and doesn't support tap?), NRE play/pause is moved into header buttons.

**Comment by OctoNezd** [comment]
> Is it possible to re-enable the res subreddit manager as it's superior to the left swipe menu and scroll to the bottom to access your sub reddit.

Moved into #79
