### ISSUE TITLE
[Reddit Premium Feature] Support reddit themes / subreddit css

### ISSUE THREAD

**Issue by Rupurudu** [OctoNezd/oldlander#7]
A limitation of using a WebExtension is that WebExtensions are not widely adopted on mobile. Using [Reddit themes](https://www.reddit.com/r/goldbenefits/comments/33ei8y/introducing_reddit_themes_change_the_appearance/) can be a possible workaround.

While I did not tested it, (I don't have premium) In theory it allows using a subreddit's theme globally except the user preferences page.

I am wondering if it's viable to make a css-only variant of this addon. I did a test and here are the limitations using this approach:

- No javascript: It may be impossible to implement some of the functionality this WebEx does using only CSS.
- No custom fonts: Reddit does not allow `@font-face`. This means no fontawesome and we must use png sheet for icons.
- No vars: Reddit does not support css vars: `unknown function "var"`. This is not a big issue since we can preproccess css.

**Comment by OctoNezd** [comment]
There are 2 extra issues on top of that:
- Addon requires viewport meta HTML code, without it website will look like a desktop site 
- Sidebar is handled via JS, not sure how can this be ported to CSS

**Comment by Rupurudu** [comment]
> In addition to the reddit themes requiring premium - this requires donating to reddit, which is a very questionable choice in current situation

Yeah, this is why I couldn't test if it works. Donating reddit $$$ right now is a very bad idea. But it might be useful to people who might already have premium. (Or after June 30, if everything else fails.)



> There are 2 extra issues on top of that:
> 
> * Addon requires [viewport meta HTML code](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag), without it website will look like a desktop site with everything being small

It seems like this is the biggest issue so far. We could use [@viewport](https://www.w3.org/TR/css-device-adapt/#atviewport-rule) rule instead of the meta tag, but of course reddit does not allow this as well.
```
[line 1] @viewport is not allowed
@viewport { width: 320px; }
```
I guess we can partially mitigate this by designing the overall ui to be bigger? Most mobile browsers use 960px width layout in desktop mode. Or maybe the solution is to not use pixels in the design and instead use `rem` or even `in` or `mm` I've never used those in a web design, and they will come with their own unique challenges, but it might be a interesting solution.

> * Sidebar is handled via JS, not sure how can this be ported to CSS

Hiding the sidebar can be handled in other ways. The easiest method comes to my mind is putting it outside of the viewport and allow vertical scrolling, so the user can ~~scroll~~ "swipe right" to show the sidebar

```
body {
  overflow: scroll;
}
.side {
  top: 0;
  right: -310px;
  position: absolute;
}
```

**Comment by OctoNezd** [comment]
In addition, @viewport is IE/EdgeHTML-only:
https://caniuse.com/?search=%40viewport

**Comment by OctoNezd** [comment]
Sadly, while this would been nice to implement if reddit were to give free custom CSS to all, it still will be too much work, and cause too many issues - especially considering custom CSS on subreddits.
