### ISSUE TITLE
Remove RandomNSFW button

### ISSUE THREAD

**Issue by zakimohzani** [OctoNezd/oldlander#71]
**Is your feature request related to a problem? Please describe.**
I dont like NSFW subreddits and especially that RandomNSFW button.

**Describe the solution you'd like**
Add option to hide/remove the RandomNSFW button

**Describe alternatives you've considered**
None

**Comment by OctoNezd** [comment]
Will try to implement toggle for that this weekend.

**Comment by zakimohzani** [comment]
Thank you for considering this idea
________________________________

**Comment by OctoNezd** [comment]
![image](https://github.com/OctoNezd/oldlander/assets/15308404/b08e814e-5141-438c-aa40-9374577be05c)
Will be available in next release.

That was quite a long weekend.

**Comment by zakimohzani** [comment]
Thanks for this. I cant wait to try it out.
________________________________
