### ISSUE TITLE
Subscribed Subreddit List Doesnt Update after Login

### ISSUE THREAD

**Issue by SamOhrenberg** [OctoNezd/oldlander#72]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this is a Bug or a Feature. I like to look at my list of subscribed subreddits in order to look for specific communities that I want to look for specific content for. The subreddits section of the sidenav doesn't display anything, but I'm not sure if that is supposed to. 

**Describe the solution you'd like**
If it's possible, I would love to see the list of Subreddits that I'm subscribed to in the side nav.

**Describe alternatives you've considered**
Honestly, any way to see the list of subreddits I'm subscibed to would be great. 

**Additional context**
I'm using Firefox Beta on a Pixel 5.

**Comment by SamOhrenberg** [comment]
Well, i logged on this morning and they were there now. Is there a delay or something involved with how long it takes from subscription to when it is displayed?

**Comment by OctoNezd** [comment]
IIRC I implemented 12-hour cache? It was long since I touched this project so I dont remember

**Comment by SamOhrenberg** [comment]
Oh that would make sense. Thanks
