### ISSUE TITLE
ChromeXt xposed/lsposed module enables userscripts for all chromium based browsers on mobile

### ISSUE THREAD

**Issue by G-D-B-9-9** [OctoNezd/oldlander#74]
https://github.com/JingMatrix/ChromeXt/

xposed / lsposed can be installed without root too.

Search github for xposed and or lsposed if interested

Extensions (chrome web store) support might come later to ChromeXt

**Comment by OctoNezd** [comment]
Interesting project - I am not a Chrome user, but it probably should work fine with userscript version of extension. Did you try it?

**Comment by G-D-B-9-9** [comment]
Yes userscripts works though the management is poor at the moment
