### ISSUE TITLE
Code blocks don't have dark theming

### ISSUE THREAD

**Issue by Jamesernator** [OctoNezd/oldlander#76]
**Describe the bug**

Code blocks don't have dark theming making them fairly illegible.

**To Reproduce**

When in dark theme, view any embedded code block.

**Expected behavior**

Code blocks should be themed.

**Screenshots**

![Screenshot_20231230-083513](https://github.com/OctoNezd/oldlander/assets/8518303/124defbc-fe53-4e96-8524-a7e517b2aa08)

**Desktop (please complete the following information):**
 - OS: Android
 - Browser Firefox
 - Version 121

**Comment by OctoNezd** [comment]
Fixed in https://github.com/OctoNezd/oldlander/commit/cffb32ad02eb2deafc1cbc5db70c5abafe5c6e84
