### ISSUE TITLE
Thumbnails changed position from right to left

### ISSUE THREAD

**Issue by heyquentin** [OctoNezd/oldlander#84]
**Describe the bug**
I opened Firefox Beta and loaded old reddit and discovered that the thumbnails are on the left now instead of the right. How do I change that?

**To Reproduce**
I wish I knew.

**Expected behavior**
Thumbnails are on the right.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 14
 - Firefox Beta
 - Version 122.0b4

**Comment by OctoNezd** [comment]
Most likely a culprit - https://github.com/OctoNezd/oldlander/commit/d54485142b94ec73ea909b05d45366c08a86d431

Weirdly, it didnt show up on my desktop during development, but shows up on my phone.
