### ISSUE TITLE
Upvoting a post does not make the up arrow orange

### ISSUE THREAD

**Issue by potatoleek** [OctoNezd/oldlander#86]
**Describe the bug**
Upvoting a post does not make the up arrow orange. Refreshing the page after upvoting a post will correctly show the orange up arrow.

**To Reproduce**
1. Click the up arrow next to a post to upvote it.
2. Notice that the up arrow remains grey.

**Expected behavior**
The up arrow should turn orange.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 12
 - Browser: Firefox 121

**Additional context**
OldLander version 1.1.0.225

**Comment by OctoNezd** [comment]
Looking at what happens during upvote, for some reason reddit JS thinks the vote was already cast, and sends 0 to undo upvote

**Comment by OctoNezd** [comment]
![image](https://github.com/OctoNezd/oldlander/assets/15308404/f4787f9e-149d-4abc-bf3d-edeb4d8344bf)
that seems to be happening due to missing some variable being set

**Comment by OctoNezd** [comment]
![image](https://github.com/OctoNezd/oldlander/assets/15308404/84bde44f-ca02-40e8-89c0-600e62217c49)
i assume we dont set up some variable during re-construction of postContainer.js

**Comment by OctoNezd** [comment]
Though in debugger both of these variables are set and work correctly

**Comment by OctoNezd** [comment]
Guess I will reimplement votes, they looked way out of place anyway.

**Comment by OctoNezd** [comment]
The issue occurs in e.fn.updateThing in reddit-init

**Comment by OctoNezd** [comment]
Scope in normal reddit:
![image](https://github.com/OctoNezd/oldlander/assets/15308404/d2e23638-38d8-4d7c-9f8d-6adb68ae4dd9)
Scope in oldlander:
![image](https://github.com/OctoNezd/oldlander/assets/15308404/9ddc016d-239f-4732-b684-cdcf802eb3db)

Reimplementing votes would require using API or somehow obtaining all the hashes generated by reddit scripts which may change

**Comment by OctoNezd** [comment]
Apparently hashes can be obtained via window.r.config, gonna try that and hope reddit wont break it later on.
