### ISSUE TITLE
Posts with lots of comments are extremely slow

### ISSUE THREAD

**Issue by faraplay** [OctoNezd/oldlander#88]
**Describe the bug**
Viewing posts with lots of (e.g. >200) comments is very slow to load.
This means that the custom icons for upvoting/downvoting, saving, etc do not appear for ages (often over 20 seconds!).
See the following screenshot as an example of how it looks while loading.

<img src="https://github.com/OctoNezd/oldlander/assets/65869253/a10b3d21-3647-4b8f-8cc2-a6fc2401c58c" width="412">

I think I've identified two main causes of the slowness:
1. The use of `waitForAllElements` in `setupGenericToggle` in `src/features/posts/postToggles.ts`. Reverting `setupGenericToggle` to how it was before commit cbbc277 greatly reduces load times, probably because it no longer has to query the entire document and set up MutationObservers 200+ times. Another way to reduce the load time might be able to call `waitAllElements` just once, by suitably modifying the selector so that it selects the save-button/hide-button of every post and comment (I haven't tested this).
2. The function `setupPost` in `src/features/posts/index.ts` always creates a postContainer div by calling `setupPostContainer`. This creates a new div, which takes a nontrivial amount of resources when you call it for over 200 comments. Since the postContainer div is only used to contain the expando button, which never exists for comments, it may be faster to check the `post` argument is a post rather than a comment (e.g. by checking it has class `link`, or it does not have class `comment`) before calling `setupPostContainer` and the expando functions.

**Comment by OctoNezd** [comment]
postContainer div is used to contain not just expando now, but also the buttons, so that they would not be bound by `.entry`

**Comment by faraplay** [comment]
Is that just for styling? If so you could probably just add extra rules to override what reddit does with the buttons.
In any case, point 1 seems to be the main problem, not point 2.

**Comment by OctoNezd** [comment]
> Is that just for styling? If so you could probably just add extra rules to override what reddit does with the buttons. In any case, point 1 seems to be the main problem, not point 2.

Well, I tried different rules to no success. Buttons are inside .entry component, so the midcol (which is now removed) on left and thumbnail on right wont let them go fullwidth

**Comment by faraplay** [comment]
Oh ok, I was looking at the buttons on comments and couldn't see much difference.
My suggestion was that we use the postContainer for links (posts) but not comments, so the buttons would still be full width for links.

**Comment by faraplay** [comment]
Please check pull request #92 and see what you think

**Comment by OctoNezd** [comment]
Looks good
