### ISSUE TITLE
Add link to subreddit from post

### ISSUE THREAD

**Issue by faraplay** [OctoNezd/oldlander#90]
**Is your feature request related to a problem? Please describe.**
Currently, when viewing a post there is no link to its subreddit.

**Describe the solution you'd like**
Maybe make the header (which has the name of the subreddit) link to the subreddit.

**Comment by Dayman22** [comment]
![Screenshot_20240104_175142_Firefox Beta](https://github.com/OctoNezd/oldlander/assets/20583488/4e99b85f-aff1-417f-a9ea-055a7a30d875)
The subreddit name in the right swipe bar has a link to the subreddit

**Comment by OctoNezd** [comment]
Thats kinda unintuitive though. I will make subreddit name clickable in header.
