### ISSUE TITLE
Certain page takes over 10 seconds to load on mobile

### ISSUE THREAD

**Issue by narinishi** [OctoNezd/oldlander#91]
**Describe the bug**
Certain page takes over 10 seconds to load

**To Reproduce**
1. Go to https://old.reddit.com/r/pics/comments/18yayqp/a_small_selection_of_portaits_done_with_the_fuji/
2. Wait for it to fully load

**Expected behavior**
I would expect it to load much quicker, and it does with OldLander disabled.

**Screenshots**
N/A

**Smartphone**
 - Browser: Firefox Nightly
 - Version #2015995559 with OldLander 1.1.0.262 installed through Tampermonkey

**Comment by faraplay** [comment]
Possible duplicate of #88 ?
When I tested it (on version 1.1.0.262 but through the Firefox extension) it took 4.29 seconds to load which seems acceptable.

**Comment by narinishi** [comment]
Thanks, it seems improved with the latest build
