### ISSUE TITLE
Unable to scroll after opening video post

### ISSUE THREAD

**Issue by Dayman22** [OctoNezd/oldlander#94]
After expanding most video posts I am unable to scroll until I open either the left or right swipe bar.

This happens on v.redd.it and streamable posts. Could affect more also

Occurs on both main page and when opening video from comments pages.

**To Reproduce**
1. Go to https://old.reddit.com/r/oddlysatisfying/comments/18ylhs6/creation_of_ceiling_art_using_plaster/
2. Expand video
3. Unable to scroll up or down
4. Close video
5. Still are unable to scroll
6. Open and close a side panels (left or right)
7. Can scroll again 

**Smartphone**
 - Device: Galaxy S21
 - OS: Android 
 - Browser Firefox Beta
 - Version 1.1.0.447

**Reddit page where bug can be easily reproduced**
https://old.reddit.com/r/oddlysatisfying/comments/18ylhs6/creation_of_ceiling_art_using_plaster/

**Comment by meekmeekmeek** [comment]
Consistently happens to me too: 

    Device: Pixel 6 Pro
    OS: Android 14 (5.10.177)
    Browser Firefox 121.0
    Version latest from today

**Comment by OctoNezd** [comment]
Fixed in https://github.com/OctoNezd/oldlander/commit/4130885001dfcb527508cc9a4b7485142bbf79ef
