### ISSUE TITLE
Option to disable Swipe gestures for Sidebar and Subreddit list 

### ISSUE THREAD

**Issue by meekmeekmeek** [OctoNezd/oldlander#95]
**Is your feature request related to a problem? Please describe.**
Currently the left/right swipe gestures to pull up the side bars from either side are incredibly sensitive, to the point that I will accidentally trigger them several times a minute just trying to quickly scroll down my feed. It seems any slight deviation from a perfectly vertical swipe is interpreted as a left or right swipe, and causes the subreddit list to jump out and cover my entire screen. Maybe it's worse on large devices, but it happens to me constantly when I'm holding my phone by one corner and swiping upwards using my thumb. 

Note that this only happens on Oldlander-modified pages. Firefox's default swipe gestures to trigger the Forward/Back functionality are far less sensitive, and only trigger when I explicitly make a side to side swipe. 

**Describe the solution you'd like**
Either reduce the sensitivity for the sideways swipe gestures, or provide an option to disable them. I personally would be fine being able to disable them as the rare times I want the subreddit list or other options I am happy to hit the Hamburger menu or the Info menu icons. 

**Describe alternatives you've considered**
Writing a Userscript to delete the sidebar html elements. 

**Additional context**
![Screenshot_20240104-212530](https://github.com/OctoNezd/oldlander/assets/12884611/bd897221-14fd-4ae5-b5df-c83cb5694dd9)

**Comment by OctoNezd** [comment]
Increased swipe threshold, added option to disable swipes.

**Comment by meekmeekmeek** [comment]
Woohoo, thanks for the very quick fix. Just the threshold change was enough to eliminate the accidental activations, but the option to disable them too is appreciated.
