### ISSUE TITLE
Scale UI elements according to System/Browser Font Size settings 

### ISSUE THREAD

**Issue by meekmeekmeek** [OctoNezd/oldlander#96]
**Is your feature request related to a problem? Please describe.**
This is more a mild annoyance than a problem, but the UI elements and icons seem to be statically sized, making them comically large if the device is using a small system font size. 

**Describe the solution you'd like**
Ideally scale the elements dynamically according to a browser font size setting. 

**Describe alternatives you've considered**
Alternatively provide a UI size override option so we can manually set how much to scale them up or down. 

Another alternative would be letting me hide some of the per-post shortcut icons. I personally don't really use the share/copy/report links often enough to need a big shortcut for them under ever post's title, so if they remain their current sizes, I'd like to at least hide some of them to declutter the page so I can see and click the things i actually want to see (title, subreddit name, poster name, thumbnail, comments count) 

**Additional context**
Screenshots below of: 

My homepage under default scaling - notice how the icons for "Save" and "Share" are something like 3x the height of the post's subreddit link, when the latter is probably much more frequently looked at 
![Screenshot_20240104-213116](https://github.com/OctoNezd/oldlander/assets/12884611/76aef7eb-e5b1-4b73-8c9a-6453852b4c67)

My Firefox accessibility settings, at default. I can override this to make the text bigger at least which makes things look less silly, but means there is less stuff on screen, and also exacerbates the issue with inline image expandos flowing off screen: 
![Screenshot_20240104-213216](https://github.com/OctoNezd/oldlander/assets/12884611/b3cc3e19-2198-4a34-a676-8517c028faaa)

My Android 14 "Display Size & Text" settings screen 
![Screenshot_20240104-214550](https://github.com/OctoNezd/oldlander/assets/12884611/7991d45f-d4f2-4ee2-964a-5cd62a7fb1f0)

*Device* Pixel 6 Pro 
*OS* Android 14 (5.10.177-android13-4-00003-ga7208022a7ea-ab10815828
#1 Fri Sep 15 16:40:54 UTC 2023)
*Browser* Firefox 121.0 (Build #2015991663),

**Comment by OctoNezd** [comment]
Hmm. I probably only applied icon-size to comments by accident.

**Comment by OctoNezd** [comment]
Nope. The post buttons are set to 2rem, while comments are 1rem. At 1.5rem post buttons look way too awkward. I will implement the ability to disable specific icons later on.
