### ISSUE TITLE
Scrolling broken after clicking on a post.

### ISSUE THREAD

**Issue by FlumSM** [OctoNezd/oldlander#97]
**To Reproduce**
1. Go to 'r/livestreamfail'
2. Click on 'the thumbnail on any of the posts to open the player then close it'
3. You can no longer scroll the screen

**Reddit page where bug can be easily reproduced**
https://old.reddit.com/r/LivestreamFail/

**Additional context**
On Mull/Fennec (firefox) browser on android

**Comment by OctoNezd** [comment]
Fixed
